# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.provision "shell", path: "sc.sh" 
  config.vm.define "ldapserver" do |ldapserver|
    ldapserver.vm.box = "centos/6"
    ldapserver.vm.hostname = "ldapserver.mnt.lab"
    ldapserver.vm.network "private_network", ip: "192.168.33.95"
    ldapserver.vm.provider "virtualbox" do |cfg|
      cfg.name = "ldapserver-cfg"
      cfg.cpus = 1
      cfg.memory = 3128
    end
  end
  
  config.vm.define "ldapclient" do |ldapclient|
    ldapclient.vm.box = "centos/6"
    ldapclient.vm.hostname = "ldapclient.mnt.lab"
    ldapclient.vm.network "private_network", ip: "192.168.33.90"
    ldapclient.vm.provider "virtualbox" do |cfg|
      cfg.name = "ldapclient-cfg"
      cfg.cpus = 1
      cfg.memory = 2048
    end
  end
end
